[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[env]
PKG_CONFIG_ALLOW_CROSS = "1"

[build]
jobs = 8
incremental = true

[net]
git-fetch-with-cli = true

[target.x86_64-unknown-linux-gnu]
# rustc-wrapper = "sccache"  # 取消注释以启用 sccache

[target.x86_64-apple-darwin]
# rustc-wrapper = "sccache"  # 取消注释以启用 sccache

[target.x86_64-pc-windows-msvc]
# rustc-wrapper = "sccache"  # 取消注释以启用 sccache
